models.py
import re
from time import time
from datetime import datetime
from app import db

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern,'-',s)

posts_tags = db.Table('posts_tags',db.Column('post_id', db.Integer,db.ForeignKey('post.id')),
                                    db.Column('tag_id',db.Integer,db.ForeignKey('tag.id')))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag',secondary='posts_tags',backref=db.backref('post'),lazy='dynamic')
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()
        
    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))
            
    def __repr__(self) -> str:
        return f'<Post id: {self.id}, title: {self.title}>'
    

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)

forms.py
from flask_wtf import FlaskForm, CSRFProtect
from wtforms import StringField,DateTimeField,SubmitField
from wtforms.validators import Email, DataRequired
from datetime import datetime


class PostForm(FlaskForm):
    title = StringField('Title', id='title', validators=[DataRequired()])
    slug = StringField('Slug',id='slug')
    body = StringField('Body', id='body')
    created = DateTimeField("Date",default=datetime.now())
    
    class Meta:
        CSRFProtect = False
        csrf = False
        SubmitField= False
        
        
class TagForm(FlaskForm):
    body = StringField('Title', id='title', validators=[DataRequired()])

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_migrate import Migrate

# https://www.youtube.com/watch?v=v6b4tggM7M0&list=PLe4mIUXfbIqaLWrzsSDQAAK3_NQB1jBZZ&index=5
'''
flask db init
flask db migrate -m "Initial migration"
flask db upgrade
'''

app = Flask(__name__,template_folder='templates', static_folder='static')
app.config.from_object(Config)

db = SQLAlchemy(app)

with app.app_context():
    db.create_all()
    Migrate(app, db).init_app(app, db)

main.py
from app import app
from app import db
from posts.blueprint import posts
from flask_bootstrap import Bootstrap5
import views

Bootstrap5(app)
app.register_blueprint(posts)

@app.before_first_request
def create_tables():
    db.create_all()

if __name__ ==  "__main__":
    app.run(debug=True)

posts/blueprint.py
from flask import Blueprint,render_template,request,redirect,url_for
from models import Post,Tag
from forms import PostForm,TagForm
from app import db


posts = Blueprint('posts',__name__,template_folder='templates',url_prefix='/blog')


@posts.route('/posts_list',methods=['GET','POST'])
def posts_list():
    post_form = PostForm(request.form)
    tagForm = TagForm(request.form)
    
    p = Post(**request.form)
    db.session.add(p)
    
    db.session.commit()
    
    posts = Post.query.all()
    tags = Tag.query.all()
    return render_template('posts_list.html',post=posts, tags=tags, tagForm=tagForm, form=post_form )

@posts.route('/postBlog')
def postBlog():
    post_form = PostForm(request.form)
    print(post_form)
    p = Post(**request.form)
    # p = Post(title=form.get('title'),body=form.get('body'),slug=form.get('slug'))
    db.session.add(p)
    db.session.commit()
    # form = PostForm()
    return render_template('posts_list.html',form=post_form)

@posts.route('/tagPost')
def tagPost():
    tagForm = TagForm(request.form)
    
    t = Tag(**request.form)
    db.session.add(t)
    db.session.commit()
    tags = Tag.query.all()
    return render_template('tag.html',tagForm=tagForm,tags= tags)

views.py
from app import app

from flask import render_template
from SmartApi import SmartConnect
import pyotp

file    = open("secret.txt").read().split()
api_key = file[0]
secret_key = file[1]
client_code = file[2]
secret_token = file[3]
password = file[4]

obj=SmartConnect(api_key=api_key)
data = obj.generateSession(client_code,password,pyotp.TOTP(file[3]).now())
feed_token = obj.getfeedToken()

@app.route('/')
def home():
    positions = obj.position()['data']
    return render_template('positions.html',context=positions)

@app.route('/login')
def login():
    return render_template('loginPopup.html')

templates/loginPopup.html
{% block head %}
<link rel="stylesheet" href="{{url_for('static',filename='loginPopup.css')}}">
{% endblock head %}
<body>
    <h2>Login page</h2>
    <button class="open-button" onclick="openForm()">Login Here</button>

         <div class="form-popup" id="myForm">
            <form action="/" class="form-container">
                <h3 style="align-self: center; position: relative; text-align: center;">Login</h3>
                <label for="username"><b>Use Name</b></label>
                <input type="text" name="username" id="username" placeholder="username">

                <label for="password"><b>Password</b></label>
                <input type="password" name="password" id="password" placeholder="password">
                <p class="paragr" style="flex-wrap: wrap; font-size:smaller;">By clicking login you agree to our <a href="http://">Terms & Conditions</a> and you have read our <a href="http://">Privacy Policy</a></p>
                <button type="submit" class="btn">Login</button>
                <button type="button" class="btn-cancel" onclick="closeForm()">Close</button>
            </form>
        </div>
    <script>
        function openForm(){
            document.getElementById("myForm").style.display="block";
        }
        function closeForm(){
            document.getElementById("myForm").style.display = "none"
        }
    </script>
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static',filename='positions.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='loginPopup.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
   <title>
    {% block title %}
    {% endblock title %}
    </title>
    {% endblock head %}
</head>
<body>
    
    <header>
        <h2 class="logo">Logo</h2>
        <nav class="navigation">
            <a href="{{ url_for('home')}}">Home</a>
            <a href="#">About</a>
            <a href="{{ url_for('posts.posts_list')}}">Blog</a>
            <a href="{{ url_for('posts.tagPost')}}">Tag</a>
            <button class="btnLogin-popup"><a href="{{ url_for('login')}}">Login</a></button>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}

</body>
</html>

templates/positions.html
{%  extends "nav.html" %}

{% block content %}

    <main id="mainPositions">
        {% if context %}
        {% for pos in context %}
        <section class="pos-first">
            <div class="positions">{{ pos['symbolname']}}</div>
            <div class="positions" style="background-color: rgb(91, 90, 90); border-radius: 5px; font-size: small;">{{ pos['exchange']}}</div>
            <div class="positions">{{ pos['expirydate']}}</div>
            {% if pos['pnl'] | float >0 %}
            <div class="positions" style="color: green;">+{{ pos['pnl']}}</div>
            {% else %}
            <div class="positions text-danger" style="color:rgb(255, 0,0, 0.7);">{{ pos['pnl']}}</div>
            {% endif %}
        </section>
        <section class="pos-second">
            <div class="pos-lower" style="background-color: rgb(91, 90, 90); border-radius: 5px; font-size: small;">CLOSED</div>
            <div class="pos-lower" style="background-color: rgb(91, 90, 90); border-radius: 5px; font-size: small;">CF</div>
            <div class="pos-lower" style="color: green;">B</div>
            <div class="pos-lower">{{ pos['totalbuyavgprice']}}</div>
            <div class="pos-lower" style="color: red;">S</div>
            <div class="pos-lower">{{ pos['totalsellavgprice']}}</div>
            <div class="pos-lower"> <span style="text-decoration: solid;">LTP </span> &shy {{ pos['ltp']}}</div>
        </section>
        {% endfor %}
        {% else %}
        <h2>No open positions found</h4>
        {% endif %}
    </main>
    
{% endblock content %}
</body>    
</html>